// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enableSpectrum": boolean;
      "enableLens": boolean;
      "enableRefract": boolean;
      "enableBeam": boolean;
      "spectrum.heatmap": boolean;
      "spectrum.heatmapColor": string;
      "spectrum.boldUnread": boolean;
      "spectrum.progressColumn": boolean;
      "spectrum.tagsColumn": boolean;
      "spectrum.hashTagColumn": boolean;
      "spectrum.hashTagPrefix": string;
      "spectrum.hashTagMap": string;
      "spectrum.rankColumn": boolean;
      "spectrum.rankFields": string;
      "spectrum.rankMap": string;
      "spectrum.easyScholarKey": string;
      "spectrum.citedColumn": boolean;
      "spectrum.citedSource": string;
      "spectrum.citedMap": string;
      "spectrum.ratingColumn": boolean;
      "spectrum.viewGroups": string;
      "spectrum.annotationColors": string;
      "spectrum.tabGroups": string;
      "spectrum.matrixFields": string;
      "lens.provider": string;
      "lens.baseURL": string;
      "lens.fullURL": boolean;
      "lens.apiKey": string;
      "lens.model": string;
      "lens.temperature": string;
      "lens.maxTokens": number;
      "lens.stream": boolean;
      "lens.profiles": string;
      "lens.systemPrompt": string;
      "lens.embedBaseURL": string;
      "lens.embedApiKey": string;
      "lens.embedModel": string;
      "lens.chunkSize": number;
      "lens.chunkOverlap": number;
      "lens.topK": number;
      "lens.bridgeEnabled": boolean;
      "lens.bridgeTarget": string;
      "lens.prompts": string;
      "lens.panelWidth": number;
      "lens.panelFontSize": number;
      "lens.readerBindMode": string;
      "lens.annotationWriteBack": boolean;
      "lens.provenance": boolean;
      "refract.engine": string;
      "refract.targetLang": string;
      "refract.sourceLang": string;
      "refract.alignment": string;
      "refract.engineFallback": boolean;
      "refract.keepFormulas": boolean;
      "refract.bodyOnly": boolean;
      "refract.skipReferences": boolean;
      "refract.skipCaptions": boolean;
      "refract.fontSize": number;
      "refract.lineHeight": string;
      "refract.fontFamily": string;
      "refract.concurrency": number;
      "refract.engineKeys": string;
      "refract.hoverOriginal": boolean;
      "refract.selectionPopup": boolean;
      "refract.autoTranslateTitle": boolean;
      "refract.layoutService": string;
      "refract.layoutServiceType": string;
      "refract.layoutServiceKey": string;
      "refract.cacheEnabled": boolean;
      "beam.rhythmGoalMinutes": number;
      "beam.review": boolean;
      "beam.reviewDaily": number;
      "beam.reviewIntervals": string;
      "beam.gapMinHits": number;
      "beam.watchlist": string;
      "beam.watchIntervalHours": number;
      "beam.lastWatchRun": number;
    };
  }
}
